name: ktlint-pr-comments

description: Run Ktlint in all added/modified .kt files and make comments for any errors
author: Leonidas Partsas

branding:
  icon: file-text
  color: blue

runs:
  using: 'docker'
  image: 'docker://le0nidas/ktlint-pr-comments:main'

inputs:
  repotoken:
    description: A token that grands access to read/write actions. Usually secrets.GITHUB_TOKEN.
    required: true

  arguments:
    description: Arguments to pass to ktlint. Note you cannot set your own --reporter argument, it will be ignored
    required: false