name: Check PR

on:
  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  checking:
    runs-on: ubuntu-latest

    steps:
      - name: Get code from repository
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Compile project
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test

      - name: Run ktlint on .kt changes
        uses: './'
        with:
          repotoken: ${{ secrets.GITHUB_TOKEN }}